[package]
name = "ParallelViz"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
hound = "3"
rustfft = "6"
cpal = "0.15"
egui = { version = "0.27", features = ["default_fonts"] }
rayon = "1.8"
