[package]
name = "ParallelViz"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4", features = ["derive"] }
hound = "3"
realfft = "3"
rodio = "0.17"
rustfft = "6"
eframe = "0.27"
egui = "0.27"
